# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190529_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=800)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedNotes',
            fields=[
                ('notes_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.Notes')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CreatedReminders',
            fields=[
                ('reminder_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.ReminderDetails')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserInfo')),
            ],
        ),
    ]
